Added Resources to project  (#178)
* disabled "SA1633:File should have header"

* fixed issues according to code analysers.

* fixed issues according to code analysers.

* fixed issues according to code analysers.

* Changed all Lists to be read-only

* fixed issues according to code analysers.

* fixed issues according to code analysers.

* modified all ILists to readonly.

* moved classes from ManageViewModels.cs to new inividual files.

* modified all ILists<> to read-only

* moved all classes from AccountViewModels.cs to new individual files.

* fixed issues according to code analysers.

* fixed formatting.

* fixed formatting

* fixed formatting

* fixed issues according to code analysers

* fixed issues according to code analysers

* fixed issues according to code analysers

* moved  class TotalTestResultEntryVmComparer to new file

* fixed issues according to code analysers

* fixed formatting

* fixed issues according to code analysers

* fixed formatting

* fixed issues according to code analysers

* fixed formatting

* fixed formatting.

* fixed issues according to code analysers.

* fixed formatting

* fixed issues according to code analysers.

* fixed issues according to code analysers.

* fixed issues according to code analysers.

* disabled rule SA1633

* disabled rule SA1601

* fixed issues according to code analysers.

* fixed issues according to code analysers.

* fixed issues according to code analysers.

* fixed issues according to code analysers

* fixed issues according to code analysers

* fixed formatting

* fixed formatting

* added analyzers and default ruleset

* updated analyzers ruleset file

* add nessesery comment on the top and remove pragma warnings

* Deleted All GlobalSuppressions.cs files

* fixed issues according to code analysers

* fixed error  CA2201: Do not raise reserved exception types

* deleted unnecesscary files

* fixed issues according to code analysers

* fixed issues according to code analysers

* fixed issues according to code analysers

* fixed issues according to code analysers

* fixed issues according to code analysers

* fixed issues according to code analysers

* fixed issues according to code analysers

*  moved public class HashParameters to new file

* fixed issues according to code analysers

* fixed issues according to code analysers

* update files according to suggestions

* Add Validation and remove pragma warnings

* add validation

* fixed errors

* fixed problems according to sugestions

* fixed issues

* fixed all

* added null checks; fixed notimplementedexceptions; fixed test mappings;

* Add Resources Path

* add firt value to resources

* fixed error CS0103

* Fixed Issues according to suggestions

* Created LoggingMesseages, fixed  CA1303

* created ExeptionsMessages.resx

* fixed CS0234

* Created ExeptionsMessages Resources

* Add Missed values to strings

* add underscores

* Revert "after merging with develop"

This reverts commit 0453a9ac41566f96d905bc3082a2e23ff57a15e0, reversing
changes made to 0047547aae3ebac975834e214f8b08cff8e247fd.

* add changes according to suggestions

* fixed typo

* added missing files

* Fixed null checks

* revert changes

* changed "ArgumentException" to "InvalidOperationException"

* added contributing.md file

* edited

* Added Resource messages

* removed double resources

* updated resources

* Update resources

* update according to suggestions